vixipy/routes/login.py
from __future__ import annotations

from quart import (
    Blueprint,
    current_app,
    flash,
    g,
    make_response,
    request,
    redirect,
    render_template,
    url_for,
)
from quart_babel import _

from ..api.handler import pixiv_request, PixivError
from ..constants import LOGIN_PAGE_BACKGROUNDS
from ..converters import proxy
import logging
import random
import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aiohttp import ClientResponse

bp = Blueprint("login", __name__)
log = logging.getLogger("vixipy.routes.login")
COOKIE_MAXAGE = 60 * 60 * 24 * 30 * 6
#               ^    ^    ^    ^    ^
#               sec  min  hr   day  mo


@bp.route("/self/login", methods=["GET", "POST"])
async def login_page():
    return_path = request.args.get("return_to", "/")
    if g.authorized:
        return redirect(return_path)

    background = random.choice(LOGIN_PAGE_BACKGROUNDS)
    id = re.search(
        r"https:\/\/i\.pximg\.net\/c\/540x540_70\/img-master\/img\/\d{4}\/\d{2}\/\d{2}\/\d{2}\/\d{2}\/\d{2}\/(\d+)_p\d+_master1200\.jpg",
        background,
    ).group(1)

    if request.method == "POST":
        f = await request.form
        token = f["token"]
        return_path = f.get("return_to", "/")

        try:
            await pixiv_request("/ajax/user/extra", cookies={"PHPSESSID": token})
            log.debug("Login success, get CSRF next...")
        except PixivError:
            await flash(_("Invalid token"), "error")
            return await render_template("login.html.j2", bg=proxy(background), id=id)

        if current_app.config["PIXIV_DIRECT_CONNECTION"]:
            r: ClientResponse = await current_app.pixiv.get(
                "",
                allow_redirects=True,
                headers={"Cookie": f"PHPSESSID={token}"},
                server_hostname="www.pixiv.net",
            )
            unauth_r: ClientResponse = await current_app.pixiv.get(
                "", allow_redirects=True, server_hostname="www.pixiv.net"
            )
        else:
            r: ClientResponse = await current_app.pixiv.get(
                "", allow_redirects=True, headers={"Cookie": f"PHPSESSID={token}"}
            )
            unauth_r: ClientResponse = await current_app.pixiv.get(
                "", allow_redirects=True
            )

        r.raise_for_status()
        t = await r.text()

        try:
            csrf = re.search(r'\\"token\\":\\"([0-9a-f]+)\\"', t).group(1)
        except IndexError:
            await flash(_("Unable to extract CSRF"))
            return await render_template("login.html.j2", bg=proxy(background), id=id)

        p_ab_id = r.cookies["p_ab_id"].value
        p_ab_id_2 = r.cookies["p_ab_id_2"].value
        p_ab_d_id = r.cookies["p_ab_d_id"].value
        yuid_b = unauth_r.cookies["yuid_b"].value
        log.debug("Extracted necessary info:")
        log.debug("csrf = %s", csrf)
        log.debug("p_ab_id = %s", p_ab_id)
        log.debug("p_ab_id_2 = %s", p_ab_id_2)
        log.debug("p_ab_d_id = %s", p_ab_d_id)

        res = await make_response(redirect(return_path))
        res.set_cookie("Vixipy-Token", token, max_age=COOKIE_MAXAGE, httponly=True)
        res.set_cookie("Vixipy-CSRF", csrf, max_age=COOKIE_MAXAGE, httponly=True)
        res.set_cookie("Vixipy-p_ab_id", p_ab_id, max_age=COOKIE_MAXAGE, httponly=True)
        res.set_cookie("Vixipy-yuid_b", yuid_b, max_age=COOKIE_MAXAGE, httponly=True)
        res.set_cookie(
            "Vixipy-p_ab_id_2", p_ab_id_2, max_age=COOKIE_MAXAGE, httponly=True
        )
        res.set_cookie(
            "Vixipy-p_ab_d_id", p_ab_d_id, max_age=COOKIE_MAXAGE, httponly=True
        )
        return res

    return await render_template("login.html.j2", bg=proxy(background), id=id)

vixipy/routes/settings.py
from __future__ import annotations

from quart import (
    Blueprint,
    g,
    redirect,
    request,
    render_template,
    url_for,
    current_app,
    make_response,
)

from ..api.handler import pixiv_request
from ..constants import REGIONS
import babel
import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Optional

bp = Blueprint("settings", __name__)
log = logging.getLogger("vixipy.routes.settings")

MAX_AGE = 60 * 60 * 24 * 30 * 6


class TranslationCredit:
    def __init__(
        self,
        name: str,
        languages: list[str],
        link: Optional[str] = None,
        profile_img: Optional[str] = None,
    ):
        self.name: str = name
        self.languages: list[str] = languages
        self.link: Optional[str] = link
        self.profile_img: Optional[str] = profile_img

    def __repr__(self):
        return (
            "<TranslationCredit "
            f"name={self.name} "
            f"languages={self.languages} "
            f"link={self.link} "
            f"profile_img={self.profile_img}>"
        )

    def translate_languages(self, language_code):
        self.languages = [
            babel.Locale(x).get_display_name(language_code) for x in self.languages
        ]


@bp.route("/settings")
async def main():
    proxies = [
        "https://pximg.bloat.cat",
        "https://pixiv.ducks.party",
        "https://pximg.cocomi.eu.org",
        "https://i.suimoe.com",
        "https://i.yuki.sh",
        "https://pximg.obfs.dev",
        "https://pixiv.darkness.services",
        "https://pi.169889.xyz",
        "https://i.pixiv.re",
    ]

    return await render_template(
        "settings/main.html.j2",
        proxies=proxies,
        is_instance_custom_proxy_server=not current_app.config["IMG_PROXY"].startswith(
            "/proxy/i.pximg.net"
        ),
        themes=current_app.config["ADDITIONAL_THEMES"]
        + current_app.config["DEFAULT_THEMES"],
    )


@bp.post("/settings/set_proxy_server")
async def set_proxy_server():
    f = await request.form
    r = await make_response(redirect(url_for("settings.main"), code=303))
    r.set_cookie("Vixipy-Image-Proxy", f["proxy"], max_age=MAX_AGE, httponly=True)
    return r


@bp.post("/settings/set_color")
async def set_color():
    f = await request.form
    r = await make_response(redirect(url_for("settings.main"), code=303))
    r.set_cookie("Vixipy-Theme", f["color"], max_age=MAX_AGE, httponly=True)
    return r


@bp.route("/settings/account")
async def account():
    if g.authorized:
        account_data = await pixiv_request("/ajax/settings/self")
        return await render_template("settings/account.html.j2", account_data=account_data)
    else:
        return await render_template("settings/account.html.j2")


@bp.route("/settings/viewing")
async def viewing():
    if not current_app.no_token or g.authorized:
        capabilities_data = await pixiv_request(
            "/ajax/settings/self", ignore_cache=True
        )

        can_view_sensitive = (
            not current_app.config["NO_SENSITIVE"]
            and capabilities_data["user_status"]["sensitive_view_setting"] == 1
        )
        can_view_ai = not capabilities_data["user_status"]["hide_ai_works"]
        can_view_r18 = (
            can_view_sensitive
            and not current_app.config["NO_R18"]
            and int(capabilities_data["user_status"]["user_x_restrict"]) >= 1
        )
        can_view_r18g = (
            can_view_r18
            and int(capabilities_data["user_status"]["user_x_restrict"]) == 2
        )
    else:
        can_view_sensitive = not current_app.config["NO_SENSITIVE"]
        can_view_r18 = can_view_r18g = not current_app.config["NO_R18"]
        can_view_ai = True

    return await render_template(
        "settings/display.html.j2",
        ai=can_view_ai,
        r18=can_view_r18,
        r18g=can_view_r18g,
        sensitive=can_view_sensitive,
        no_token=current_app.no_token,
    )


@bp.post("/settings/set_content_filter")
async def set_content_filter():
    f = await request.form
    r = await make_response(redirect(url_for("settings.viewing"), code=303))
    r.set_cookie(
        "Vixipy-No-AI",
        str(int(not f.get("hide-ai") == "on")),
        max_age=MAX_AGE,
        httponly=True,
    )

    r18g = not f.get("hide-r18g") == "on"
    r18 = not f.get("hide-r18") == "on"
    sensitive = not f.get("hide-sensitive") == "on"
    preview = f.get("preview-mode") == "on"
    blur = f.get("blur") == "on"

    log.debug((sensitive, r18, r18g))

    r.set_cookie(
        "Vixipy-No-R18",
        str(int(r18)),
        max_age=MAX_AGE,
        httponly=True,
    )
    r.set_cookie(
        "Vixipy-No-R18G",
        str(int(r18g)),
        max_age=MAX_AGE,
        httponly=True,
    )
    r.set_cookie(
        "Vixipy-No-Sensitive",
        str(int(sensitive)),
        max_age=MAX_AGE,
        httponly=True,
    )
    r.set_cookie(
        "Vixipy-Preview-Mode",
        str(int(preview)),
        max_age=MAX_AGE,
        httponly=True,
    )
    r.set_cookie(
        "Vixipy-Blur-Sensitive", str(int(blur)), max_age=MAX_AGE, httponly=True
    )

    return r


@bp.route("/settings/language-and-location")
async def language_location():
    if g.authorized:
        region = (await pixiv_request("/ajax/settings/self", ignore_cache=True))[
            "user_status"
        ]["location"]
    else:
        region = None

    if l := request.cookies.get("Vixipy-Language"):
        current_lang = l
    else:
        current_lang = "en"

    locale = babel.Locale(current_lang)
    region_opts = {x: locale.territories[x] for x in REGIONS}

    langs = {x: babel.Locale(x).language_name for x in current_app.config["LANGUAGES"]}
    return await render_template(
        "settings/language.html.j2", langs=langs, regions=region_opts, region=region
    )


@bp.post("/settings/set_language")
async def set_language():
    f = await request.form
    r = await make_response(redirect(url_for("settings.language_location"), code=303))
    r.set_cookie("Vixipy-Language", f["lang"], max_age=MAX_AGE, httponly=True)
    return r


@bp.post("/settings/set_region")
async def setLocation():
    form = await request.form
    region = form["region"]

    resp = await make_response(
        redirect(url_for("settings.language_location"), code=303)
    )

    await pixiv_request(
        "/ajax/settings/location", "post", json_payload={"location": region}
    )
    return resp


@bp.get("/settings/about")
async def about_page():
    return await render_template("settings/about.html.j2")


@bp.get("/settings/acknowledgements")
async def acknowledgements():
    language = request.cookies.get("Vixipy-Language", "en") or "en"
    TRANSLATION_CREDITS: list[TranslationCredit] = {
        TranslationCredit(
            "Vyxie",
            ["fil", "ja"],
            "https://codeberg.org/kita",
            "/proxy/3rd_party/profile_image/codeberg/kita",
        ),
        TranslationCredit(
            "cutekita",
            ["de"],
            "https://github.com/cutekita",
            "/proxy/3rd_party/profile_image/github/cutekita",
        ),
        TranslationCredit("SomeTr", ["uk", "de"], "https://codeberg.org/SomeTr"),
        TranslationCredit("Poesty Li", ["zh_Hans"], "https://codeberg.org/poesty"),
        TranslationCredit(
            "Hayden",
            ["zh_Hans"],
            "https://codeberg.org/haydenwu",
            "/proxy/3rd_party/profile_image/codeberg/haydenwu",
        ),
        TranslationCredit("lainie", ["ru"], "https://laincorp.tech"),
        TranslationCredit(
            "Oliver Tzeng",
            ["zh_Hant"],
            "https://github.com/olivertzeng",
            "/proxy/3rd_party/profile_image/github/olivertzeng",
        ),
    }

    for x in TRANSLATION_CREDITS:
        x.translate_languages(language)

    return await render_template(
        "settings/acknowledgements.html.j2",
        i18n_cred=sorted(TRANSLATION_CREDITS, key=lambda _: _.name),
    )


@bp.get("/license")
async def license():
    return await render_template("license/index.html.j2")

vixipy/templates/settings/about.html.j2
{% extends "settings/index.html.j2" %}
{% set settings_title = _("About Vixipy") %}

{% block settings_content %}
<h3>{{_("About Vixipy")}}</h3>
<p>{{_("Vixipy is a free and open source alternative <a href='%(link)s'>pixiv</a> frontend, allowing you to view and enjoy works from pixiv distraction-free without unnecessary bloat and tracking.", link="https://en.wikipedia.org/wiki/pixiv")}}</p>
<p>{{_("If you like our work, please consider <a href='%(link)s'>giving us a star</a> on Codeberg!", link="https://codeberg.org/vixipy/Vixipy")}}</p>

<h3>{{_("Why use it?")}}</h3>
<ul>
    <li>{{_("Vixipy allows you to browse pixiv anonymously with all restrictions removed (including the ability to view original resolution artworks). No pixiv account required to access content.")}}</li>
    <li>{{_("Vixipy does all the work for you: no connection to pixiv or any third-party server is made and all processing occurs server-side. No more Google Analytics tracking for every action!")}}</li>
    <li>{{_("Vixipy offers a lightweight and fast experience without any distraction.")}}</li>
    <li>{{_("Vixipy is free and open source, meaning anyone can audit, contribute, modify, or use it without restriction (as long as you follow its <a href='%(license_link)s'>license</a>).", license_link='/license#vixipy')}}</li>
</ul>

<h3>{{_("How does it work?")}}</h3>
<p>{{_("Vixipy retrieves content using pixiv's API, parses it, and displays the results through own user interface. You remain completely anonymous if you use public instances as all requests are handled server side, and blends in with other activities in the instance.")}}</p>
<p>{{_("Even if you log in, pixiv will only see you as if you are using their official UI, but without any tracking (the same behaviour if you use a content blocker such as uBlock Origin)")}}</p>

<h3>{{_("How do I make it my own?")}}</h3>
<p>{{_("If you want to host your own for personal (if you are concerned about logs) or public use, you can self-host your own instance, fully within your control.")}}</p>
<p>{{_("Vixipy can essentially run on almost any platform and operating system (such as Windows, Linux, FreeBSD, Haiku, Android, and many more), as long as it can run Python 3.11 and above, and can compile Vixipy's native dependencies.")}}</p>

<p><i><a href="{{url_for('settings.acknowledgements')}}">{{_("Acknowledgements")}}</a></i></p>

{% endblock %}

vixipy/templates/settings/account.html.j2
{% extends "settings/index.html.j2" %}
{% set settings_title = _("Account") %}

{% block settings_content %}
<h3>{{_("Account")}}</h3>
{%- if g.authorized -%}
<div class="info">
    <h3 class="title">{{_("Manage pixiv account")}}</h3>
    <p>{{_("To manage your account information and security settings, go to the official Account Portal")}}</p>
    <a href="/jump.php?url=https://accounts.pixiv.net/portal" rel="noopener noreferrer" target="_blank">
        <strong>{{_("Go to Account Portal")}}</strong>
    </a>
</div>
<hr>
<section>
    <div>{{"Nickname"}}</div>
    <main>
        <strong>{{account_data["user_status"]["user_name"]}}</strong>
        <br>
        <br>
        <small class="tip">{{_("You change your nickname and customize your profile in the <a href='%(link)s'>Profile editor</a>.", link=url_for("profile_edit.edit_profile"))}}</small>
    </main>
</section>
<section>
    <div>{{_("Account Token")}}</div>
    <main>
        <div class="hidden-content">
            <input type="checkbox" id="token-r">
            <label for="token-r">{{_("Click to reveal")}}</label>
            <main>
                <code>{{request.cookies.get("Vixipy-Token")}}</code>
            </main>
        </div>
        <small class="tip">{{_("This is the token used to sign into your pixiv account. You may use this if you forget your token or want to move instances or pixiv frontends.")}}</small>
    </main>
</section>
<section>
    <div>{{_("Email")}}</div>
    <main>
        <div class="hidden-content">
            <input type="checkbox" id="email-r">
            <label for="email-r">{{_("Click to reveal")}}</label>
            <main>
                <strong>{{account_data["user_status"]["user_mail_address"]}}</strong>
            </main>
        </div>
    </main>
</section>
<section>
    <div>pixiv ID</div>
    <main>
        {%- set handle = account_data["user_status"]["user_account"] -%}
        <strong>{{handle}}</strong>
        <br><br>
        <small class="tip">{{_('The pixiv ID is your "account handle", which is served as a short vanity link to your account. Example: pixiv.me/%(handle)s (or %(example)s for Vixipy). ', handle=handle, example=request.host + "/@" + handle)}}</small>
    </main>
</section>
<h3>{{_("Technical information")}}</h3>
<section>
    <div>{{_("CSRF Token")}}</div>
    <main>
        <div class="hidden-content">
            <input type="checkbox" id="csrf-r">
            <label for="csrf-r">{{_("Click to reveal")}}</label>
            <main>
                <code>{{request.cookies.get("Vixipy-CSRF")}}</code>
            </main>
        </div>
    </main>
</section>
<section>
    <div>{{_("pixiv A/B test IDs")}}</div>
    <main>
        <span>id: <code>{{request.cookies.get("Vixipy-p_ab_id")}}</code>, id_2: <code>{{request.cookies.get("Vixipy-p_ab_id_2")}}</code>, d_id: <code>{{request.cookies.get("Vixipy-p_ab_d_id")}}</code></span>
    </main>
</section>
<section>
    <div>yuid_b</div>
    <main>
        <code>{{request.cookies.get("Vixipy-yuid_b")}}</code>
    </main>
</section>
{%- else -%}
<div class="info">
    <h3 class="title">{{_("You're not logged in")}}</h3>
    <p>{{_("Sign in to your pixiv account to experience Vixipy to it's full potential. Don't worry, we won't steal your session tokens!")}}</p>
    <a href="{{url_for('login.login_page', return_to=url_for('settings.account'))}}"><strong>{{_("Sign in")}}</strong></a>
</div>
{%- endif -%}
{% endblock %}

vixipy/templates/settings/acknowledgements.html.j2
{% extends "settings/index.html.j2" %}
{% set settings_title = _("Acknowledgements") %}

{% block settings_content %}
<h3>{{_("Acknowledgements")}}</h3>

<p>{{_("These projects and libraries help shape Vixipy:")}}</p>

<p><i>{{_("This section has been moved to the <a href='%(link)s'>Licenses page</a>.", link=url_for("settings.license"))}}</i></p>

<h4>{{_("Translations")}}</h4>
<p>{{_("These lovely people helped translate Vixipy (thank you so much &lt;3):")}}</p>
<ul class="translators-list">
    {% for x in i18n_cred %}
    <li>
        <a {% if x.link %}href="{{x.link}}"{% endif %}>
            <img src="{{ x.profile_img or '/proxy/s.pximg.net/common/images/no_profile.png' }}" alt="{{x.name}}">
            <main>
                <strong>{{x.name}}</strong>
                <small>{{x.languages|join(', ')}}</small>
            </main>
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

vixipy/templates/settings/display.html.j2
{% extends "settings/index.html.j2" %}
{% set settings_title = _("Display settings") %}

{% block settings_content %}
<h3>{{_("Display settings")}}</h3>
<section>
    <div>
        {{_("Work content")}}
    </div>
    <main>
        <form action="/settings/set_content_filter" method="post">
            {%- set ai_enabled = c.get("Vixipy-No-AI", 0)|int == 1 -%}
            {%- set r18_enabled = c.get("Vixipy-No-R18", 0)|int == 1 -%}
            {%- set r18g_enabled = c.get("Vixipy-No-R18G", 0)|int == 1 -%}
            {%- set sensitive_enabled = c.get("Vixipy-No-Sensitive", 0)|int == 1 -%}
            {%- set preview_enabled = c.get("Vixipy-Preview-Mode", 0)|int == 1 -%}
            {%- set blur_enabled = c.get("Vixipy-Blur-Sensitive", 0)|int == 1 -%}

            <label class="toggle-switch">
                <input type="checkbox" name="hide-ai"
                    {% if ai %}{% if not ai_enabled %}checked{% endif %}{% else %}disabled{% endif %}
                > {{_("Show AI-generated work")}}
            </label>
            <label class="toggle-switch">
                <input type="checkbox" name="hide-sensitive" 
                    {% if not config["NO_SENSITIVE"] %}{% if not sensitive_enabled %}checked{% endif %}{% else %}disabled{% endif %}> {{_("Display works that may contain sensitive content")}}
            </label>
            <label class="toggle-switch">
                <input type="checkbox" name="hide-r18"
                    {% if r18 %}{% if not r18_enabled %}checked{% endif %}{% else %}disabled{% endif %}> {{_("Show explicit content (R-18)")}}
            </label>
            <label class="toggle-switch">
                <input type="checkbox" name="hide-r18g"
                    {% if r18g %}{% if not r18g_enabled %}checked{% endif %}{% else %}disabled{% endif %}> {{_("Show ero-guro content (R-18G)")}}
            </label>
            <label class="toggle-switch">
                <input type="checkbox" name="preview-mode"
                    {% if preview_enabled %}checked{% endif %}> {{_("Hide artwork thumbnails (preview mode)")}}
            </label>
            <label class="toggle-switch">
                <input type="checkbox" name="blur"
                    {% if blur_enabled %}checked{% endif %}> {{_("Blur sensitive works (may cause performance issues!)")}}
            </label>
            <br>
            <button class="button smaller neutral" type="submit">{{_("Save preferences")}}</button>
        </form>
    </main>
</section>
<section>
    <div>{{_("Ad display settings")}}</div>
    <main>
        <label class="toggle-switch">
            <input type="checkbox" disabled> {{_("Display")}}
        </label>
    </main>
</section>
{% endblock %}

vixipy/templates/settings/index.html.j2
{% extends "layouts/default.html.j2" %}
{% if settings_title %}
{% set title =  settings_title + " | " + _("Settings") %}
{% else %}
{% set title = _("Settings") %}
{% endif %}

{% set c = request.cookies %}

{% block content %}
<main class="no-transition" id="settings">
    <div class="menu">
        <h2>{{_("Settings")}}</h2>
        <nav>
            <a href="/settings">{{_("Vixipy settings")}}</a>
            <a href="/settings/account">{{_("Account")}}</a>
            <a href="/settings/viewing">{{_("Display settings")}}</a>
            <a href="/settings/language-and-location">{{_("Language and location")}}</a>
            <a href="/settings/about">{{_("About Vixipy")}}</a>
            <a href="/license">{{_("Licenses")}}</a>
        </nav>
    </div>
    <div class="content">
        {% block settings_content %}{% endblock %}
    </div>
</main>
{% endblock %}

vixipy/templates/settings/language.html.j2
{% extends "settings/index.html.j2" %}
{% set settings_title = _("Language and location") %}

{% block settings_content %}
<h3>{{_("Language and location")}}</h3>
<section>
    <div>
        {{_("Language")}}
    </div>
    <main>
        <form action="/settings/set_language" method="post">
            <select name="lang" class="width-100">
		        <option value="" {% if not request.cookies.get("Vixipy-Language", "") %}selected{%endif%}>{{_("Use system language")}}</option>
		        {% for l in langs %}
		        <option value="{{l}}" {%if request.cookies.get("Vixipy-Language") == l%}selected{%endif%}>{{langs[l]}}</option>
		        {% endfor %}
            </select>
	        <br><br>
	        <a href="https://translate.codeberg.org/engage/vixipy/">{{_("Help translate Vixipy to your language!")}}</a>
            <br><br>
            <button class="button smaller neutral" type="submit">{{_("Set language")}}</button>
        </form>
    </main>
</section>
{%- if g.authorized -%}
<section>
    <div>{{_("Location")}}</div>
    <form action="/settings/set_region" method="post">
        <select name="region" class="width-100">
            {%- for x in regions -%}
            <option value="{{x}}" {% if region == x %}selected{% endif %}>{{regions[x]}}</option>
            {%- endfor -%}
        </select>
        <br><br>
        <button type="submit" class="button smaller neutral">{{_("Set location")}}</button>
    </form>
</section>
{%- endif -%}
{% endblock %}

vixipy/templates/settings/main.html.j2
{% extends "settings/index.html.j2" %}
{% set section = "preferences" %}
{% set settings_title = _("Vixipy settings") %}

{% block settings_content %}
<h3>{{_("Vixipy settings")}}</h3>
<section>
    <div>
        {{_("Image Proxy Server")}}
    </div>
    <main>
        <form action="/settings/set_proxy_server" method="post" hx-boost="false">
            <select name="proxy" class="width-100">
                {% if is_instance_custom_proxy_server %}
                <option value="" {% if c.get('Vixipy-Image-Proxy') == None or c.get('Vixipy-Image-Proxy') == '' %}selected{%endif%}>{{_("Use proxy specified by instance")}}</option>
                <option value="/proxy/i.pximg.net" {% if c.get('Vixipy-Image-Proxy') == '/proxy/i.pximg.net' %}selected{%endif%}>{{_("Use built-in proxy")}}</option>
                {% else %}
                <option value="" {% if not c.get('Vixipy-Image-Proxy') %}selected{%endif%}>{{_("Use built-in proxy")}}</option>
                {% endif %}

                {% for i in proxies %}
                <option value="{{i}}" {% if c.get('Vixipy-Image-Proxy') == i %}selected{% endif %}>{{i}}</option>
                {% endfor %}
            </select>
	    <br><br>
            <small class="tip">{{_("An image proxy allows retrieving images from pixiv without making any connection to pixiv servers.")}}</small>
            <br><br>
            <button class="button smaller neutral" type="submit">{{_("Use selected proxy")}}</button>
        </form>
    </main>
</section>
<section>
    <div>
        {{_("Color Scheme")}}
    </div>
    <main>
        <form action="/settings/set_color" method="post"  hx-boost="false">
            {%- set ct = request.cookies.get("Vixipy-Theme") -%}
            <select class="width-100" name="color" id="">
                <option value="" {% if not ct %}selected{%endif%}>{{_("Default")}}</option>
                {% for x in themes %}
                <option value="{{x}}" {% if x == ct %}selected{% endif %}>{{x}}</option>
                {% endfor %}
            </select>
            <br><br>
            
            <button class="button smaller neutral" type="submit">{{_("Set color scheme")}}</button>
        </form>
    </main>
</section>
{% endblock %}