vixipy/lib/pixivision/__init__.py
from __future__ import annotations

from .parser import *
from ._types import *
from ...converters import proxy, convert_pixiv_link

import asyncio
from bs4 import BeautifulSoup
from http import HTTPStatus
import logging
from quart import abort, current_app, request
import time
from typing import TYPE_CHECKING, Callable


log = logging.getLogger("vixipy.lib.pixivision")


def get_preferred_language():
    mapping = {"en": "en", "ja": "ja", "ko": "ko", "zh_Hans": "zh", "zh_Hant": "zh-tw"}

    if l := request.args.get("lang"):
        if l not in mapping.values():
            abort(400)
        return l
    if c := request.cookies.get("Vixipy-Preferred-Pixivision-Language"):
        return c
    else:
        return mapping.get(request.cookies.get("Vixipy-Language"), "en")


async def _run_in_ex(func: Callable, *args):
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)


async def _pixivision_request(endpoint, params: dict[str, str] = {}) -> BeautifulSoup:
    language = get_preferred_language()

    start = time.perf_counter()

    r = await current_app.pixivision.get(
        f"/{language}{endpoint}",
        params=params,
        headers={"Cookie": f"user_lang={language.replace('-', '_')};"},
    )

    req_done = time.perf_counter()

    log.info(
        "[%dms] %s %s",
        (req_done - start) * 1000,
        endpoint,
        str(HTTPStatus(r.status)),
    )

    r.raise_for_status()
    data = await r.text()

    r.close()

    req_finish = time.perf_counter()

    log.info(
        "[%dms] [done] %s",
        (req_finish - start) * 1000,
        endpoint,
    )

    s = BeautifulSoup(data, "html.parser")

    for x in s.find_all("a"):
        x.attrs["href"] = convert_pixiv_link(x.attrs["href"])

    for x in s.find_all("img"):
        x.attrs["src"] = proxy(x.attrs["src"])

    for x in s.find_all("iframe"):
        x.attrs["src"] = convert_pixiv_link(x.attrs["src"])

    init_parse_finish = time.perf_counter()

    log.info(
        "[%dms] [parsed] %s",
        (init_parse_finish - start) * 1000,
        endpoint,
    )

    return s


async def get_landing_page(page: int = 1):
    d = await _pixivision_request("/", {"p": page})
    spotlight, articles, pg = await asyncio.gather(
        _run_in_ex(parse_spotlight, d),
        _run_in_ex(parse_article_entries, d),
        _run_in_ex(get_pagination_capabilities, d),
    )

    if spotlight:
        spotlight.image = proxy(spotlight.image)

    for x in articles:
        x.image = proxy(x.image)

    return PixivisionLanding(spotlight, articles, pg)


async def search(term: str, page: int = 1):
    d = await _pixivision_request("/s", {"q": term, "p": page})
    res, pg = await asyncio.gather(
        _run_in_ex(parse_article_entries, d),
        _run_in_ex(get_pagination_capabilities, d),
    )

    for x in res:
        x.image = proxy(x.image)

    return res, pg


async def get_article(id: int):
    d = await _pixivision_request(f"/a/{id}")
    res = await _run_in_ex(parse_article, d)
    return res


async def get_tag(id: int, page: int = 1):
    d = await _pixivision_request(f"/t/{id}", {"p": page})
    res, pg = await asyncio.gather(
        _run_in_ex(parse_article_entries, d),
        _run_in_ex(get_pagination_capabilities, d),
    )

    for x in res:
        x.image = proxy(x.image)

    return res, pg


async def get_category(id: int, page: int = 1):
    d = await _pixivision_request(f"/c/{id}", {"p": page})
    res, pg = await asyncio.gather(
        _run_in_ex(parse_article_entries, d),
        _run_in_ex(get_pagination_capabilities, d),
    )

    for x in res:
        x.image = proxy(x.image)

    return res, pg

vixipy/routes/pixivision.py
from ..lib.pixivision import (
    get_landing_page,
    get_article,
    get_tag,
    get_category,
    search as search_pixivion,
)

from quart import Blueprint, render_template, request
from quart_rate_limiter import limit_blueprint, timedelta

bp = Blueprint("pixivision", __name__)
limit_blueprint(bp, 1, timedelta(seconds=5))


@bp.route("/pixivision")
async def main():
    data = await get_landing_page(int(request.args.get("p", 1)))

    return await render_template("pixivision/index.html.j2", data=data)


@bp.route("/pixivision/a/<int:id>")
async def article(id: int):
    data = await get_article(id)
    return await render_template("pixivision/article.html.j2", data=data)


@bp.route("/pixivision/t/<int:id>")
async def tag(id: int):
    data, pg = await get_tag(id, int(request.args.get("p", 1)))
    return await render_template("pixivision/tag.html.j2", data=data, pg=pg, id=id)


@bp.route("/pixivision/s/")
async def search():
    data, pg = await search_pixivion(request.args["q"], int(request.args.get("p", 1)))
    return await render_template("pixivision/search.html.j2", data=data, pg=pg)


@bp.route("/pixivision/c/<c>")
async def category(c: str):
    data, pg = await get_category(c, int(request.args.get("p", 1)))
    return await render_template("pixivision/category.html.j2", data=data, pg=pg, c=c)

vixipy/templates/pixivision/article.html.j2
{% extends "layouts/default.html.j2" %}
{% set title = data.title %}

{% from "pixivision/category_name.html.j2" import category %}

{% block head_additional %}
<meta property="og:title" content="{{data.title}}">
<meta property="og:description" content="{{data.og_desc}}">
<meta property="og:image" content="{{data.og_img}}">
<meta property="og:site_name" content="{{config['INSTANCE_NAME']}}">
<meta name="twitter:card" content="summary_large_image">
{% endblock %}

{% block content %}
<main id="pixivision-article">
    <div class="article-meta">
        <div class="info">
            <a class="category"
                href="{{url_for('pixivision.category', c=data.category.value)}}">{{category(data.category)}}</a>
            <time datetime="{{data.date.strftime('%Y-%m-%d')}}">{{data.date|dateformat}}</time>
        </div>
        <h1>{{data.title}}</h1>
    </div>
    <article>
        {% for x in data.contents %}
        {{x.render()|safe}}
        {% endfor %}
    </article>
</main>
{% endblock %}

vixipy/templates/pixivision/category.html.j2
{% extends "layouts/default.html.j2" %}
{% from "pixivision/category_name.html.j2" import category %}
{% from "pixivision/entry.html.j2" import pxvs_entry %}

{% set title = category(c) + " | " + _("pixivision") %}

{% block content %}
<main id="pixivision">
    <h1>{{_('Articles in category "%(c)s"', c=category(c))}}</h1>

    <div class="articles">
        {% for x in data %}
        {{pxvs_entry(x)}}
        {% endfor %}
    </div>

    {% if pg[0] or pg[1] %}
    <div class="paginator">
        {%- set page = request.args.get("p", 1)|int -%}
        <a {% if pg[0] %}href="{{url_for('pixivision.category', c=c, p=page-1)}}" {% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3">
                <path
                    d="m432-480 156 156q11 11 11 28t-11 28q-11 11-28 11t-28-11L348-452q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l184-184q11-11 28-11t28 11q11 11 11 28t-11 28L432-480Z" />
            </svg>
        </a>
        <span>{{_("Page %(page)d", page=page)}}</span>
        <a {% if pg[1] %}href="{{url_for('pixivision.category', c=c, p=page+1)}}" {% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3">
                <path
                    d="M504-480 348-636q-11-11-11-28t11-28q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L404-268q-11 11-28 11t-28-11q-11-11-11-28t11-28l156-156Z" />
            </svg>
        </a>
    </div>
    {% endif %}
</main>
{% endblock %}

vixipy/templates/pixivision/category_name.html
{%- macro category(id) %}

{% set i = id.value or id %}

{% if i == "illustration" %}
{{_("Illustrations")}}
{% elif i == "manga" %}
{{_("Manga")}}
{% elif i == "novels" %}
{{_("Novels")}}
{% elif i == "cosplay" %}
{{_("Cosplay")}}
{% elif i == "music" %}
{{_("Music")}}
{% elif i == "goods" %}
{{_("Goods")}}
{% elif i == "how-to-draw" %}
{{_("Tutorials")}}
{% elif i == "draw-step-by-step" %}
{{_("Behind the Art")}}
{% elif i == "textures" %}
{{_("Materials")}}
{% elif i == "art-references" %}
{{_("References")}}
{% elif i == "how-to-make" %}
{{_("Other Guides")}}
{% elif i == "recommend" %}
{{_("Featured")}}
{% elif i == "interview" %}
{{_("Interviews")}}
{% elif i == "column" %}
{{_("Columns")}}
{% elif i == "news" %}
{{_("News")}}
{% elif i == "deskwatch" %}
{{_("Deskwatch")}}
{% elif i == "try-out" %}
{{_("We Tried It!")}}
{% endif %}

{% endmacro -%}

vixipy/templates/pixivision/category_name.html.j2
{%- macro category(id) %}

{% set i = id.value or id %}

{% if i == "illustration" %}
{{_("Illustrations")}}
{% elif i == "manga" %}
{{_("Manga")}}
{% elif i == "novels" %}
{{_("Novels")}}
{% elif i == "cosplay" %}
{{_("Cosplay")}}
{% elif i == "music" %}
{{_("Music")}}
{% elif i == "goods" %}
{{_("Goods")}}
{% elif i == "how-to-draw" %}
{{_("Tutorials")}}
{% elif i == "draw-step-by-step" %}
{{_("Behind the Art")}}
{% elif i == "textures" %}
{{_("Materials")}}
{% elif i == "art-references" %}
{{_("References")}}
{% elif i == "how-to-make" %}
{{_("Other Guides")}}
{% elif i == "recommend" %}
{{_("Featured")}}
{% elif i == "interview" %}
{{_("Interviews")}}
{% elif i == "column" %}
{{_("Columns")}}
{% elif i == "news" %}
{{_("News")}}
{% elif i == "deskwatch" %}
{{_("Deskwatch")}}
{% elif i == "try-out" %}
{{_("We Tried It!")}}
{% endif %}

{% endmacro -%}

vixipy/templates/pixivision/entry.html.j2
{% from "pixivision/category_name.html.j2" import category %}
{%- macro pxvs_entry(data) %}
<div class="pixivision-entry">
    <div class="thumb">
        <a class="img" href="{{url_for('pixivision.article', id=data.id)}}">
            <img src="{{data.image}}" alt="{{data.title}}">
        </a>
        <a class="category" href="{{url_for('pixivision.category', c=data.category.value)}}">{{category(data.category)}}</a>
    </div>
    <div class="title">
        <a href="{{url_for('pixivision.article', id=data.id)}}">{{data.title}}</a>
    </div>
    <div class="meta">
        <ul class="tags">
            {% for x in data.tags %}
            <li><a href="{{url_for('pixivision.tag', id=x.id)}}">#{{x.name}}</a></li>
            {% endfor %}
        </ul>
        <time datetime="{{data.date.strftime('%Y-%m-%d')}}">{{data.date|dateformat}}</time>
    </div>
</div>
{% endmacro -%}

vixipy/templates/pixivision/search.html.j2
{% extends "layouts/default.html.j2" %}
{% set term = request.args["q"] %}
{% set title = _('Results for "%(term)s"', term=term) + " | " + _("pixivision") %}

{% from "pixivision/entry.html.j2" import pxvs_entry %}


{% block content %}
<main id="pixivision">
    <form action="/pixivision/s/">
        <div class="searchbox">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd"
                    d="M15.461 10.615c0-1.334-.474-2.475-1.422-3.423-.948-.949-2.09-1.423-3.424-1.423s-2.475.474-3.423 1.423c-.949.948-1.423 2.09-1.423 3.423 0 1.335.474 2.476 1.423 3.424.948.948 2.09 1.422 3.423 1.422 1.335 0 2.476-.474 3.424-1.422s1.422-2.09 1.422-3.424zm5.539 9c0 .375-.137.7-.411.974a1.33 1.33 0 01-.974.411c-.389 0-.714-.137-.973-.411l-3.71-3.7a7.407 7.407 0 01-4.317 1.342c-1.03 0-2.017-.2-2.958-.6a7.613 7.613 0 01-2.434-1.623A7.614 7.614 0 013.6 13.574c-.4-.941-.6-1.927-.6-2.959 0-1.03.2-2.017.6-2.958.4-.941.941-1.753 1.623-2.434A7.614 7.614 0 017.657 3.6c.941-.4 1.927-.6 2.958-.6 1.032 0 2.018.2 2.959.6.941.4 1.752.941 2.434 1.623a7.613 7.613 0 011.622 2.434c.4.941.6 1.927.6 2.958a7.407 7.407 0 01-1.34 4.316l3.71 3.71c.267.268.4.592.4.974z" />
            </svg>
            <input type="text" name="q" placeholder="{{_('Search pixivision...')}}" value="{{term}}">
        </div>
    </form>

    <h1>{{_('Results for "%(term)s"', term=term)}}</h1>

    <div class="articles">
        {% for x in data %}
        {{pxvs_entry(x)}}
        {% endfor %}
    </div>

    {% if pg[0] or pg[1] %}
    <div class="paginator">
        {%- set page = request.args.get("p", 1)|int -%}
        <a {% if pg[0] %}href="{{url_for('pixivision.search', q=term, p=page-1)}}" {% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3">
                <path
                    d="m432-480 156 156q11 11 11 28t-11 28q-11 11-28 11t-28-11L348-452q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l184-184q11-11 28-11t28 11q11 11 11 28t-11 28L432-480Z" />
            </svg>
        </a>
        <span>{{_("Page %(page)d", page=page)}}</span>
        <a {% if pg[1] %}href="{{url_for('pixivision.search', q=term, p=page+1)}}" {% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3">
                <path
                    d="M504-480 348-636q-11-11-11-28t11-28q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L404-268q-11 11-28 11t-28-11q-11-11-11-28t11-28l156-156Z" />
            </svg>
        </a>
    </div>
    {% endif %}
</main>
{% endblock %}

vixipy/templates/pixivision/tag.html.j2
{% extends "layouts/default.html.j2" %}
{% from "pixivision/entry.html.j2" import pxvs_entry %}

{% set title=_("List of articles with tag") %}

{% block content %}
<main id="pixivision">
    <h1>{{_("List of articles with tag")}}</h1>

    <div class="articles">
        {% for x in data %}
        {{pxvs_entry(x)}}
        {% endfor %}
    </div>

    {% if pg[0] or pg[1] %}
    <div class="paginator">
        {%- set page = request.args.get("p", 1)|int -%}
        <a {% if pg[0] %}href="{{url_for('pixivision.tag', id=id, p=page-1)}}"{% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="m432-480 156 156q11 11 11 28t-11 28q-11 11-28 11t-28-11L348-452q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l184-184q11-11 28-11t28 11q11 11 11 28t-11 28L432-480Z"/></svg>
        </a>
        <span>{{_("Page %(page)d", page=page)}}</span>
	<a {% if pg[1] %}href="{{url_for('pixivision.tag', id=id, p=page+1)}}"{% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="M504-480 348-636q-11-11-11-28t11-28q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L404-268q-11 11-28 11t-28-11q-11-11-11-28t11-28l156-156Z"/></svg>
        </a>
    </div>
    {% endif %}
</main>
{% endblock %}