vixipy/routes/user_action.py
from __future__ import annotations

from quart import Blueprint, make_response, request, redirect, url_for, g, abort

from ..api.handler import pixiv_request
from ..api.search import get_tag_info
from typing import TYPE_CHECKING
from urllib.parse import quote
from quart_babel import lazy_gettext as _l

if TYPE_CHECKING:
    from typing import Union

bp = Blueprint("user_action", __name__)

HX_HEADER = '{"X-Vixipy-Quick-Action": "true"}'  #  work around for python


@bp.before_request
async def ensure_authorized():
    if request.path == "/self/consent":
        return

    isQuickAction = request.headers.get("X-Vixipy-Quick-Action") == "true"
    if not g.get("authorized"):
        if isQuickAction:
            abort(401)
        if request.method == "POST":
            abort(401)
        return redirect(url_for("login.login_page"))


@bp.post("/self/action/user/<int:id>/<action>")
async def follow_unfollow(id: int, action: Union["follow", "unfollow"]):
    f = await request.form
    isQuickAction = request.headers.get("X-Vixipy-Quick-Action") == "true"
    rt = f.get("return_to", "/")

    if action == "follow":
        await pixiv_request(
            "/touch/ajax_api/ajax_api.php",
            "post",
            raw_payload=f"mode=add_bookmark_user&restrict=0&user_id={id}",
            headers={
                "Referer": f"https://www.pixiv.net/en/users/{id}",
                "Origin": "https://www.pixiv.net",
            },
        )
        if isQuickAction:
            return f"""
<form action="/self/action/user/{id}/unfollow"
    hx-push-url="false" hx-swap="outerHTML show:none" hx-target="this" hx-indicator="this"
    hx-headers='{HX_HEADER}' method="post">
    <input type="hidden" name="return_to" value="{rt}">
    {"<input type='hidden' name='small'>" if 'small' in f else ''}
    <button type="submit" class="button {'smaller' if 'small' in f else ''} neutral">
        {_l("Following")}
    </button>
</form>
"""
        else:
            return redirect(rt, code=303)
    elif action == "unfollow":
        await pixiv_request(
            "/touch/ajax_api/ajax_api.php",
            "post",
            raw_payload=f"mode=delete_bookmark_user&user_id={id}",
            headers={
                "Referer": f"https://www.pixiv.net/en/users/{id}",
                "Origin": "https://www.pixiv.net",
            },
        )
        if isQuickAction:
            return f"""
<form action="/self/action/user/{id}/follow"
    hx-push-url="false" hx-swap="outerHTML show:none" hx-target="this" hx-indicator="this"
    hx-headers='{HX_HEADER}' method="post">
    <input type="hidden" name="return_to" value="{rt}">
    {"<input type='hidden' name='small'>" if 'small' in f else ''}
    <button type="submit" class="button {'smaller' if 'small' in f else ''} primary">
        {_l("Follow")}
    </button>
</form>
"""
        else:
            return redirect(rt, code=303)


@bp.post("/self/action/works/<int:id>/<action>")
async def perform_work_action(id: int, action: Union["bookmark", "like"]):
    f = await request.form
    isQuickAction = request.headers.get("X-Vixipy-Quick-Action") == "true"
    withinArtwork = f.get("within_illust")
    rt = f.get("return_to", "/")

    if action == "bookmark":
        data = await pixiv_request(
            "/ajax/illusts/bookmarks/add",
            "post",
            json_payload={
                "illust_id": str(id),
                "restrict": 0,
                "comment": "",
                "tags": [],
            },
        )

        if isQuickAction:

            if withinArtwork:
                return f"""
                <form action="/self/action/delete_bookmark/{data['last_bookmark_id']}" method="post"
                    hx-swap="outerHTML show:none" hx-target="this" hx-push-url="false"
                    hx-headers='{HX_HEADER}'>

                    <input type="hidden" name="return_to" id="{request.path}">
                    <input type="hidden" name="work_id" value="{id}">
                    <input type="hidden" name="within_illust" value="1">

                    <button type="submit" class="bookmarked">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="M480-147q-14 0-28.5-5T426-168l-69-63q-106-97-191.5-192.5T80-634q0-94 63-157t157-63q53 0 100 22.5t80 61.5q33-39 80-61.5T660-854q94 0 157 63t63 157q0 115-85 211T602-230l-68 62q-11 11-25.5 16t-28.5 5Z"/></svg>
                    </button>
                </form>
                """

            return f"""
<form action="/self/action/delete_bookmark/{data['last_bookmark_id']}" method="post"
hx-swap="outerHTML show:none" hx-target="this" hx-push-url="false" hx-indicator="this"
hx-headers='{HX_HEADER}'>
    <input type="hidden" name="return_to" id="{request.path}">
    <input type="hidden" name="bookmark_count" value="{int(f["bookmark_count"]) + 1}">
    <input type="hidden" name="work_id" value="{id}">
    <button type="submit">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11 2H5a2 2 0 00-2 2v10l5-2.5 5 2.5V4a2 2 0 00-2-2z"/></svg>
        {int(f["bookmark_count"]) + 1}
    </button>
</form>
"""
        else:
            return redirect(rt, code=303)

    if action == "like":
        await pixiv_request(
            "/ajax/illusts/like", "post", json_payload={"illust_id": str(id)}
        )

        if isQuickAction:
            return f"""
<svg class="liked" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 8a2 2 0 100-4 2 2 0 000 4zM12 8a2 2 0 100-4 2 2 0 000 4zM11.89 10.89a5.5 5.5 0 01-7.78 0 1 1 0 011.415-1.415 3.5 3.5 0 004.95 0 1 1 0 111.414 1.414z"/></svg>
{int(f['like_count']) + 1}
"""
        else:
            return redirect(rt, code=303)


@bp.post("/self/action/remove_favorite_tag")
async def remove_favorite_tag():
    f = await request.form
    isQuickAction = request.headers.get("X-Vixipy-Quick-Action") == "true"
    rt = f.get("return_to", "/")
    tag = f.get("tag")

    if not tag:
        abort(400)

    tag_info = await get_tag_info(tag)
    if not tag_info.is_favorite:
        abort(400)

    tag_info.favorite_tags.remove(tag)

    await pixiv_request(
        "/ajax/favorite_tags/save",
        "post",
        json_payload={"tags": tag_info.favorite_tags},
    )

    if isQuickAction:
        return f"""
        <form id="favorites-action" action="/self/action/add_favorite_tag" method="post" hx-push-url="false"
                hx-swap="outerHTML show:none" hx-target="this" hx-headers='{HX_HEADER}'>

                <input type="hidden" name="tag" value="{tag}">
                <input type="hidden" name="return_to" value="{rt}">

                <button type="submit" class="button primary">{_l("Add to your favorites")}</button>
        </form>
        """


@bp.post("/self/action/add_favorite_tag")
async def add_favorite_tag():
    f = await request.form
    isQuickAction = request.headers.get("X-Vixipy-Quick-Action") == "true"
    rt = f.get("return_to", "/")
    tag = f.get("tag")

    if not tag:
        abort(400)

    tag_info = await get_tag_info(tag)
    if tag_info.is_favorite:
        abort(400)

    tag_info.favorite_tags.append(tag)

    await pixiv_request(
        "/ajax/favorite_tags/save",
        "post",
        json_payload={"tags": tag_info.favorite_tags},
    )

    if isQuickAction:
        return f"""
        <form id="favorites-action" action="/self/action/remove_favorite_tag" method="post" hx-push-url="false"
                hx-swap="outerHTML show:none" hx-target="this" hx-headers='{HX_HEADER}'>

                <input type="hidden" name="tag" value="{tag}">
                <input type="hidden" name="return_to" value="{rt}">

                <button type="submit" class="button neutral">{_l("Remove from favorites")}</button>
        </form>
        """


@bp.post("/self/action/delete_bookmark/<int:id>")
async def delete_bookmark(id: int):
    f = await request.form
    isQuickAction = request.headers.get("X-Vixipy-Quick-Action") == "true"
    withinArtwork = f.get("within_illust")
    rt = f.get("return_to", "/")

    await pixiv_request(
        "/ajax/illusts/bookmarks/delete", "post", raw_payload=f"bookmark_id={id}"
    )

    if isQuickAction:
        if withinArtwork:
            return f"""
                <form action="/self/action/works/{f['work_id']}/bookmark" method="post"
                    hx-swap="outerHTML show:none" hx-target="this" hx-push-url="false"
                    hx-headers='{HX_HEADER}'>

                    <input type="hidden" name="return_to" id="{request.path}">
                    <input type="hidden" name="work_id" value="{f['work_id']}">
                    <input type="hidden" name="within_illust" value="1">


                    <button type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="M480-147q-14 0-28.5-5T426-168l-69-63q-106-97-191.5-192.5T80-634q0-94 63-157t157-63q53 0 100 22.5t80 61.5q33-39 80-61.5T660-854q94 0 157 63t63 157q0 115-85 211T602-230l-68 62q-11 11-25.5 16t-28.5 5Zm-38-543q-29-41-62-62.5T300-774q-60 0-100 40t-40 100q0 52 37 110.5T285.5-410q51.5 55 106 103t88.5 79q34-31 88.5-79t106-103Q726-465 763-523.5T800-634q0-60-40-100t-100-40q-47 0-80 21.5T518-690q-7 10-17 15t-21 5q-11 0-21-5t-17-15Zm38 189Z"/></svg>
                    </button>
                </form>
                """

        return f"""
<form action="/self/action/works/{f['work_id']}/bookmark" method="post"
hx-swap="outerHTML show:none" hx-target="this" hx-push-url="false" hx-indicator="this"
hx-headers='{HX_HEADER}'>
    <input type="hidden" name="return_to" id="{request.path}">
    <input type="hidden" name="bookmark_count" value="{int(f["bookmark_count"]) - 1}">
    <input type="hidden" name="work_id" value="{f['work_id']}">

vixipy/routes/users.py
from quart import Blueprint, abort, g, redirect, render_template, request, url_for
from quart_rate_limiter import timedelta, rate_limit

from asyncio import gather
from ..api.user import (
    get_user,
    get_user_profile_top,
    get_user_illusts,
    get_user_bookmarks,
    get_user_followers,
    get_user_following,
    get_user_mypixiv,
)
from ..api.handler import pixiv_request
from ..decorators import tokenless_require_login, require_login
from ..filters import filter_from_prefs as ff
from ..abc.novels import NovelEntry

bp = Blueprint("users", __name__)


@bp.get("/users/<int:user>")
@rate_limit(1, timedelta(seconds=5))
async def user_profile(user: int):
    data, top = await gather(get_user(user, True), get_user_profile_top(user))

    return await render_template("users/top.html.j2", data=data, top=ff(top))


@bp.get("/users/<int:user>/illustrations")
@rate_limit(1, timedelta(seconds=1))
async def user_illusts(user: int):
    data, il = await gather(
        get_user(user, True), get_user_illusts(user, page=int(request.args.get("p", 1)))
    )

    il.illusts = ff(il.illusts)

    return await render_template("users/illust.html.j2", data=data, il=il)


@bp.get("/users/<int:user>/manga")
@rate_limit(2, timedelta(seconds=3))
async def user_manga(user: int):
    data, il = await gather(
        get_user(user, True),
        get_user_illusts(
            user, content_type="manga", page=int(request.args.get("p", 1))
        ),
    )

    il.illusts = ff(il.illusts)

    return await render_template("users/manga.html.j2", data=data, il=il)


@bp.get("/users/<int:user>/bookmarks")
@rate_limit(2, timedelta(seconds=3))
@tokenless_require_login
async def user_bookmarks(user: int):
    data, bkdata = await gather(
        get_user(user, True),
        get_user_bookmarks(
            user, int(request.args.get("p", 1)), request.args.get("tag", "")
        ),
    )

    pages, y = divmod(bkdata[0], 48)
    if y > 0:
        pages += 1

    return await render_template(
        "users/bookmarks.html.j2", data=data, il=ff(bkdata[1]), pages=pages
    )


@bp.get("/users/<int:user>/novels")
@rate_limit(2, timedelta(seconds=3))
async def user_novels(user: int):
    data, cts = await gather(
        get_user(user, True), pixiv_request(f"/ajax/user/{user}/profile/all")
    )

    p = int(request.args.get("p", 1))

    if len(cts["novels"]) > 0:
        novel_ids = [int(x) for x in cts["novels"].keys()]
        to_get = novel_ids[(30 * p) - 30 : 30 * p]

        ndata = await pixiv_request(
            f"/ajax/user/{user}/profile/novels", params=[("ids[]", x) for x in to_get]
        )
        novels = [NovelEntry(x) for x in ndata["works"].values()]

        pages, _ = divmod(len(novels), 30)
        if _ > 0:
            pages += 1
    else:
        novels = []
        pages = 1

    return await render_template(
        "users/novels.html.j2", data=data, novels=ff(novels), pages=pages
    )


@bp.route("/users/<int:user>/following")
@tokenless_require_login
async def following(user: int):
    user, data = await gather(
        get_user(user),
        get_user_following(
            user,
            int(request.args.get("p", 1)),
            request.args.get("rest", "show"),
            int(request.args.get("acceptingRequests", 0)),
        ),
    )

    return await render_template("users/follow/following.html.j2", user=user, data=data)


@bp.route("/users/<int:user>/followers")
@tokenless_require_login
async def followers(user: int):
    if g.current_user.id != user:
        abort(400)

    user, data = await gather(
        get_user(user), get_user_followers(user, int(request.args.get("p", 1)))
    )

    return await render_template("users/follow/followers.html.j2", user=user, data=data)


@bp.route("/users/<int:user>/mypixiv")
@tokenless_require_login
async def mypixiv(user: int):

    user, data = await gather(
        get_user(user), get_user_mypixiv(user, int(request.args.get("p", 1)))
    )

    return await render_template("users/follow/mypixiv.html.j2", user=user, data=data)


@bp.get("/u/<int:user>")
async def pixivcompat_user(user: int):
    return redirect(url_for("users.user_profile", user=user))


@bp.get("/self/actions")
async def user_dashboard():
    return await render_template("users/dashboard.html.j2")

vixipy/templates/users/follow/base.html.j2
{% extends "layouts/default.html.j2" %}
{% from "components/paginator.html.j2" import paginator %}
{%- set page = request.args.get('p', 1)|int -%}
{%- set is_self = g.authorized and g.current_user and user.id == g.current_user.id -%}

{% block content %}
<section id="prof-user-info-min">
    {% if user.background %}
    <img src="{{user.background}}">
    {% endif %}
    <main>
        <div class="wrap">
            <div class="user">
                <a href="{{url_for('users.user_profile', user=user.id)}}" class="icon-button">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M15.913 16.586a2 2 0 01-2.829 2.828L5.67 12l7.414-7.414a2 2 0 012.829 2.828L11.327 12l4.586 4.586z" fill="currentColor"/></svg>
                </a>
                <main>
                    <img src="{{user.image}}" alt="{{user.name}}">
                    <span>{{user.name}}</span>
                </main>
            </div>
        </div>
    </main>
</section>
<main class="no-transition">
    <div class="nav-controller">
        <nav class="tabs">
            <a
                {% if current == "following" %}
                href="#" class="active"
                {% else %}
                href="{{url_for('users.following', user=user.id)}}"
                {% endif %}
            >{{_("Following")}}</a>
            <a
                {% if current == "mypixiv" %}
                href="#" class="active"
                {% else %}
                href="{{url_for('users.mypixiv', user=user.id)}}"
                {% endif %}
            >{{_("My pixiv")}}</a>
            {% if is_self %}
            <a
                {% if current == "followers" %}
                href="#" class="active"
                {% else %}
                href="{{url_for('users.followers', user=user.id)}}"
                {% endif %}
            >{{_("Followers")}}</a>
            {% endif %}
        </nav>
        {% if is_self and current == 'following' %}
        <div class="chip-toggle">
            <a href="{{url_for('users.following', user=user.id, rest='show')}}" {% if request.args.get('rest', 'show') == 'show' %}class="active"{% endif %}>Public</a>
            <a href="{{url_for('users.following', user=user.id, rest='hide')}}" {% if request.args['rest'] == 'hide' %}class="active"{% endif %}>Private</a>
        </div>
        {% endif %}
    </div>
    <br>
    {% block c %}{% endblock %}
</main>
{% endblock %}

vixipy/templates/users/follow/followers.html.j2
{% extends "users/follow/base.html.j2" %}
{% from "components/user-entry.html.j2" import userentry %}
{% set title = _("%(user)s's followers", user=user.name) %}
{% set current = "followers" %}

{% block c %}
{% if data.total > 0 %}
<h3>{{_("Users (%(count)d)", count = data.total)}}</h3>
{% for x in data.users %}
{{ userentry(x.user, x.illusts) }}
{% endfor %}

{{- paginator(
    request.args.get("p", 1)|int,
    data.pages,
    url_for('users.following', user=user.id, p=page-1, rest=request.args.get('rest', 'show')),
    url_for('users.following', user=user.id, p=page+1, rest=request.args.get('rest', 'show'))
) -}}

{% else %}

<div class="no-content">
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.507 10.5a3.75 3.75 0 10-.014 0C4.459 10.504 2 12.883 2 15.818 2 16.471 2.53 17 3.182 17h7.451a5.608 5.608 0 012.21-2.445c-.585-2.325-2.752-4.052-5.336-4.055zm8.993 4a3.75 3.75 0 100-7.5 3.75 3.75 0 000 7.5zm0 0c-3.038 0-5.5 2.381-5.5 5.318V20a1 1 0 001 1h9a1 1 0 001-1v-.182c0-2.937-2.462-5.318-5.5-5.318z" fill="currentColor"/></svg>
{{_("You don't have any followers.")}}
</div>

{% endif %}
{% endblock %}

vixipy/templates/users/follow/following.html.j2
{% extends "users/follow/base.html.j2" %}
{% from "components/user-entry.html.j2" import userentry %}
{% set title = _("%(user)s's followed users", user=user.name) %}
{% set current = "following" %}

{% block c %}
{% if data.total > 0 %}
<h3>{{_("Users (%(count)d)", count = data.total)}}</h3>
{% for x in data.users %}
{{ userentry(x.user, x.illusts) }}
{% endfor %}

{{- paginator(
    request.args.get("p", 1)|int,
    data.pages,
    url_for('users.following', user=user.id, p=page-1, rest=request.args.get('rest', 'show')),
    url_for('users.following', user=user.id, p=page+1, rest=request.args.get('rest', 'show'))
) -}}

{% else %}
<div class="no-content">
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.507 10.5a3.75 3.75 0 10-.014 0C4.459 10.504 2 12.883 2 15.818 2 16.471 2.53 17 3.182 17h7.451a5.608 5.608 0 012.21-2.445c-.585-2.325-2.752-4.052-5.336-4.055zm8.993 4a3.75 3.75 0 100-7.5 3.75 3.75 0 000 7.5zm0 0c-3.038 0-5.5 2.381-5.5 5.318V20a1 1 0 001 1h9a1 1 0 001-1v-.182c0-2.937-2.462-5.318-5.5-5.318z" fill="currentColor"/></svg>
{% if is_self %}
{{_("You are not following anyone.")}}
{% else %}
{{_("%(user)s isn't following anyone.", user=user.name)}}
{% endif %}
</div>
{% endif %}
{% endblock %}

vixipy/templates/users/follow/mypixiv.html.j2
{% extends "users/follow/base.html.j2" %}
{% from "components/user-entry.html.j2" import userentry %}
{% set title = _("%(user)s's My pixiv", user=user.name) %}
{% set current = "mypixiv" %}

{% block c %}
{% if data.total > 0 %}
<h3>{{_("Users (%(count)d)", count = data.total)}}</h3>
{% for x in data.users %}
{{ userentry(x.user, x.illusts) }}
{% endfor %}

{{- paginator(
    request.args.get("p", 1)|int,
    data.pages,
    url_for('users.following', user=user.id, p=page-1, rest=request.args.get('rest', 'show')),
    url_for('users.following', user=user.id, p=page+1, rest=request.args.get('rest', 'show'))
) -}}

{% else %}
<div class="no-content">
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.507 10.5a3.75 3.75 0 10-.014 0C4.459 10.504 2 12.883 2 15.818 2 16.471 2.53 17 3.182 17h7.451a5.608 5.608 0 012.21-2.445c-.585-2.325-2.752-4.052-5.336-4.055zm8.993 4a3.75 3.75 0 100-7.5 3.75 3.75 0 000 7.5zm0 0c-3.038 0-5.5 2.381-5.5 5.318V20a1 1 0 001 1h9a1 1 0 001-1v-.182c0-2.937-2.462-5.318-5.5-5.318z" fill="currentColor"/></svg>
{% if is_self %}
{{_("You don't have any My pixiv.")}}
{% else %}
{{_("%(user)s doesn't have any My pixiv.", user=user.name)}}
{% endif %}
</div>
{% endif %}
{% endblock %}