vixipy/routes/api.py
from __future__ import annotations
from quart import Blueprint, abort, current_app, request
from quart_rate_limiter import rate_limit, timedelta

from ..api.handler import PixivError, pixiv_request
from ..api.artworks import get_artwork, get_newest_works
from ..decorators import tokenless_require_login
from ..lib.monet import scheme_from_url
import asyncio
import traceback
import logging
from typing import Union, TYPE_CHECKING
from urllib.parse import quote
from werkzeug.exceptions import (
    HTTPException,
    BadRequest,
    NotFound,
    TooManyRequests,
    Unauthorized,
    Forbidden,
)

if TYPE_CHECKING:
    from quart import Response
    from werkzeug.datastructures import ImmutableDict

bp = Blueprint("api", __name__, url_prefix="/api")
log = logging.getLogger("vixipy.routes.api")


def make_error(message: str, code: int = 500, body: Union[dict, list] = []):
    return {"error": True, "message": message, "body": body}, code


def make_json_response(message: str = "", body: Union[dict, list] = []):
    return {"error": False, "message": message, "body": body}


@bp.errorhandler(HTTPException)
async def handle_bad_request(e: HTTPException):
    code_map = {
        400: "Invalid request",
        401: "Authorization required to access endpoint",
        403: "Insufficient permission to access resource",
        404: "Resource not found or does not exist",
        405: "Method not allowed",
        429: "Too many requests. Try again another time",
    }
    return make_error(code_map.get(e.code, "Invalid request"), e.code)


@bp.errorhandler(Exception)
async def handle_errors(e: Exception):
    return make_error(
        "Exception error", body={"error": str(e), "traceback": traceback.format_exc()}
    )


@bp.after_request
async def set_header_common(r: Response):
    r.headers["Access-Control-Allow-Origin"] = "*"
    return r


@bp.route("/search/autocomplete")
async def autocomplete_handler():
    keyword = request.args["keyword"]

    data = await pixiv_request(
        "/rpc/cps.php",
        params=[("keyword", quote(keyword, safe="")), ("lang", "en")],
        headers={"Referer": "https://www.pixiv.net"},
    )

    result: list[dict] = []

    for x in data["candidates"]:
        log.debug(x)
        if x["type"] in ("romaji", "tag_translation"):
            result.append(
                {
                    "name": x["tag_name"],
                    "sub": x.get("tag_translation"),
                    "access_count": int(x["access_count"]),
                }
            )
        else:
            result.append(
                {
                    "name": x["tag_name"],
                    "sub": None,
                    "access_count": int(x["access_count"]),
                }
            )

    return make_json_response(
        body=sorted(result, key=lambda _: _["access_count"], reverse=True)
    )


@bp.route("/configuration")
async def node_info():
    account = not current_app.no_token

    try:
        git_p = await asyncio.create_subprocess_exec(
            "git",
            "rev-parse",
            "--short",
            "HEAD",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        git_o, err = await git_p.communicate()
        if err:
            raise RuntimeError(err.decode("utf-8"))
    except Exception:
        log.exception("Failure retrieving commit")
        rev = None
    else:
        rev = str(git_o.decode("utf-8")).rstrip()

    return make_json_response(
        body={
            "acceptLanguage": current_app.config["ACCEPT_LANGUAGE"],
            "commit": rev,
            "instanceName": current_app.config["INSTANCE_NAME"],
            "r18": not current_app.config["NO_SENSITIVE"]
            and not current_app.config["NO_R18"],
            "sensitiveWorks": not current_app.config["NO_SENSITIVE"],
            "ratelimiting": current_app.config["QUART_RATE_LIMITER_ENABLED"],
            "repo": "https://codeberg.org/vixipy/Vixipy",
            "usesAccount": account,
            "logHttp": current_app.config["LOG_HTTP"],
            "logPixiv": current_app.config["LOG_PIXIV"],
            "version": current_app.config["VIXIPY_VERSION"],
            "bypassCloudflare": current_app.config["PIXIV_DIRECT_CONNECTION"],
            "imageProxy": current_app.config["IMG_PROXY"],
        }
    )


@bp.get("/illust/<int:id>/ugoira_meta")
@rate_limit(1, timedelta(seconds=5))
async def ugoira_meta(id: int):
    try:
        work = await get_artwork(id)
    except PixivError as e:
        if e.code == 404:
            abort(404)
        else:
            abort(e.code)

    if not work.isUgoira:
        return make_error("Work is not ugoira", 400)

    data = await pixiv_request(f"/ajax/illust/{id}/ugoira_meta")
    return make_json_response(body=data)


@bp.get("/illust/<int:id>/material-you")
async def gen_scheme_from_artwork(id: int):
    try:
        work = await pixiv_request(f"/ajax/illust/{id}")
        scheme = request.args.get("scheme", "tonal_spot")
        img = work["urls"]["thumb"]
        if not img:
            raise Exception

        result = await scheme_from_url(img, True, scheme)

        return result, {"Content-Type": "text/css", "Cache-Control": "max-age=31536000"}
    except Exception:
        log.exception("Failure generating color scheme for ID %d", id)
        return "", {"Content-Type": "text/css"}


@bp.get("/user/<int:id>/material-you")
async def gen_scheme_from_user(id: int):
    try:
        data = await pixiv_request(f"/ajax/user/{id}")
        scheme = request.args.get("scheme", "tonal_spot")
        if background := data["background"]:

            img = background["url"]
            result = await scheme_from_url(img, True, scheme)
            return result, {
                "Content-Type": "text/css",
                "Cache-Control": "max-age=31536000",
            }

        return "", {"Content-Type": "text/css"}
    except Exception:
        log.exception("Failure generating color scheme for ID %d", id)
        return "", {"Content-Type": "text/css"}


@bp.route("/illust/new")
@tokenless_require_login
async def _get_new_works():
    args: ImmutableDict = request.args

    no_r18 = current_app.config["NO_SENSITIVE"] or current_app.config["NO_R18"]

    if no_r18 and request.args.get("r18") == "true":
        abort(403)

    try:
        data = await get_newest_works(
            type_=args.get("type", "illust"),
            r18=args.get("r18") == "true",
            last_id=args.get("last_id", 0),
        )
    except PixivError:
        abort(403)
    except Exception:
        raise

    illusts = []
    for x in data.illusts:
        illusts.append(
            {
                "id": x.id,
                "title": x.title,
                "thumb": x.thumb,
                "r18": x.r18,
                "ai": x.ai,
                "user_id": x.authorId,
                "user_name": x.authorName,
                "profile_image": x.profileimg,
                "page_count": x.pages,
                "alt": x.alt,
            }
        )
    return make_json_response(body={"last_id": data.last_id, "illusts": illusts})

vixipy/routes/artworks.py
from __future__ import annotations

from quart import (
    Blueprint,
    abort,
    current_app,
    g,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from quart_rate_limiter import limit_blueprint, timedelta, RateLimit
from asyncio import gather
from jinja2_fragments.quart import render_block
import datetime
import logging
import re
from typing import TYPE_CHECKING

from ..api.handler import PixivError
from ..api import artworks
from ..api.user import (
    get_user,
    get_user_illusts_from_ids,
)
from ..constants import EMOJI_SERIES
from ..decorators import require_login
from ..filters import filter_from_prefs as ff
from ..filters import check_blacklisted_tag
from ..abc.artworks import ArtworkPage
from ..util import is_consented
from ..lib import monet

if TYPE_CHECKING:
    from ..abc.artworks import Artwork, ArtworkEntry
    from ..abc.users import PartialUser
    from aiohttp import ClientResponse

bp = Blueprint("artworks", __name__)
log = logging.getLogger("vixipy.routes.artworks")
thumb_reg = re.compile(
    r"https?:\/\/i.pximg.net\/c\/.+\/img\/(\d{4}\/\d{2}\/\d{2}\/\d{2}\/\d{2}\/\d{2})\/(\d+)_p(\d+)_.+\.(jpg|png)"
)

limit_blueprint(
    bp, limits=[RateLimit(3, timedelta(seconds=1)), RateLimit(30, timedelta(minutes=1))]
)


async def __attempt_work_extraction(
    id: int, userIllusts: list[ArtworkEntry], pagesCount: int
):
    uil_to_dict: list[ArtworkEntry] = {int(i.id): i for i in userIllusts}
    result: list[ArtworkPage] = []

    def pz(n: int):
        if n >= 10:
            return n
        else:
            return "0" + str(n)

    log.debug(uil_to_dict)
    if id in uil_to_dict:
        log.debug(uil_to_dict[id].unproxied_thumb)
        extracted_thumb = thumb_reg.search(uil_to_dict[id].unproxied_thumb)
        if not extracted_thumb:
            log.debug("Failed to extract date from thumbnail. Trying create date...")
            d = datetime.datetime.fromisoformat(uil_to_dict[id].uploadDate_raw)

            _date = f"{d.year}/{pz(d.month)}/{pz(d.day)}/{pz(d.hour)}/{pz(d.minute)}/{pz(d.second)}"
        else:
            _date = extracted_thumb.group(1)

        for x in range(pagesCount):
            _master = f"/img-master/img/{_date}/{id}_p{x}_master1200.jpg"
            _orig = None
            for ext in ("jpg", "png", "gif"):
                _orig_uri = f"/img-original/img/{_date}/{id}_p{x}.{ext}"

                log.debug("Trying %s", _orig_uri)
                ori: ClientResponse = await current_app.content_proxy.head(
                    "https://i.pximg.net" + _orig_uri
                )
                if ori.status != 200:
                    log.debug("Did not work!")
                    continue
                else:
                    log.debug("%s works!", _orig_uri)
                    _orig = _orig_uri
                    break

            if not _orig:
                log.error("No URLs found to work. Abort.")
                continue

            result.append(
                ArtworkPage(
                    {
                        "urls": {
                            "regular": "i.pximg.net" + _master,
                            "original": "i.pximg.net" + _orig,
                        },
                        "width": "(unknown)",
                        "height": "(unknown)",
                    },
                    x + 1,
                )
            )

        return result
    else:
        log.info("Work not in userIllusts, cannot continue!")
        return []


@bp.get("/_partials/artworks/<int:id>/root")
async def _root_p(id: int):
    work: Artwork = await artworks.get_artwork(id)
    return await render_block("artworks.html.j2", "root", work=work)


@bp.get("/_partials/artworks/<int:id>/pages")
async def _pages_p(id: int):
    try:
        pages: list[ArtworkPage] = await artworks.get_artwork_pages(id)
    except Exception as e:
        return await render_block("artworks.html.j2", "page_error", error=e)
    return await render_block("artworks.html.j2", "pages", pages=pages)


@bp.get("/_partials/artworks/author/<int:id>")
async def _author_p(id: int):
    user = await get_user(id)
    return await render_block("artworks.html.j2", "author", user=user)


@bp.get("/_partials/artworks/<int:id>/recommend")
async def _recommend_p(id: int):
    data = await artworks.get_recommended_works(id)
    r = await make_response(
        await render_block("artworks.html.j2", "recommended", recommend=ff(data))
    )

    if len(data) == 0:
        r.headers["HX-Reswap"] = "delete"

    return r


@bp.get("/artworks/<int:id>")
async def _get_artwork(id: int):
    try:
        work: Artwork = await artworks.get_artwork(id)
    except PixivError as e:
        abort(e.code)

    if any([check_blacklisted_tag(x.name) for x in work.tags]):
        abort(403)

    if work.ai and bool(int(request.cookies.get("Vixipy-No-AI", 0))):
        abort(403)

    if current_app.config["NO_SENSITIVE"] and work.sl >= 4:
        abort(403)

    if (
        (
            (current_app.config["NO_R18"] or current_app.config["NO_SENSITIVE"])
            and work.xrestrict >= 1
        )
        or (bool(int(request.cookies.get("Vixipy-No-R18", 0))) and work.xrestrict >= 1)
        or (bool(int(request.cookies.get("Vixipy-No-R18G", 1))) and work.xrestrict == 2)
    ):
        abort(403)

    if (work.r18 or work.sl >= 4) and not is_consented():
        return await render_template(
            "content_warning.html.j2", url=url_for("artworks._get_artwork", id=id)
        )

    if not g.hx_request:

        if work.deficient:
            log.info("Work is deficient, trying to extract pages...")
            pages, recommend, user, works = await gather(
                __attempt_work_extraction(id, work.other_works, work.pages),
                artworks.get_recommended_works(id),
                get_user(work.authorId),
                get_user_illusts_from_ids(work.authorId, work.works_missing[:50]),
            )

            if len(pages) == 0:
                log.fatal("Artwork returned no pages. Bailing out!")
                abort(404)
        else:
            pages, recommend, user, works = await gather(
                artworks.get_artwork_pages(id),
                artworks.get_recommended_works(id),
                get_user(work.authorId),
                get_user_illusts_from_ids(work.authorId, work.works_missing[:50]),
            )

        pages: list[ArtworkPage]
        recommend: list[ArtworkEntry]
        user: PartialUser
        works: list[ArtworkEntry]

        return await render_template(
            "artworks.html.j2",
            work=work,
            pages=pages,
            recommend=ff(recommend),
            user=user,
            user_works=ff(sorted(works + work.other_works, key=lambda _: int(_.id))),
        )

    return await render_template("artworks.html.j2", work=work)


@bp.get("/artworks/<int:id>/comments")
async def get_comments(id: int):
    work, data = await gather(
        artworks.get_artwork(id), artworks.get_artwork_comments(id, int(request.args.get("p", 1)))
    )
    return await render_template(
        "comments.html.j2", work=work, data=data, id=id, emojis=EMOJI_SERIES
    )


@bp.get("/artworks/replies/<int:id>")
async def get_replies(id: int):
    data = await artworks.get_artwork_replies(id, int(request.args.get("p", 1)))
    return await render_template("replies.html.j2", data=data, id=id)


@bp.get("/a/<int:id>")
async def redirect_shortlink(id: int):
    return redirect(url_for("artworks._get_artwork", id=id))


@bp.get("/artworks/series/<int:id>")
async def series(id: int):
    data = await artworks.get_illust_series(id, int(request.args.get("p", 1)))
    return await render_template("illust_series.html.j2", data=data)


@bp.post("/self/action/series/<int:id>/<op>")
@require_login
async def act_illust_series(id: int, op: str):
    f = await request.form

    mp = {
        "watch": artworks.watch_illust_series,
        "unwatch": artworks.unwatch_illust_series,
        "notify": artworks.notify_illust_series,
        "unnotify": artworks.remove_notify_illust_series
    }

    fn = mp.get(op)
    if fn is None:
        abort(400)


    await fn(id)
    data = await artworks.get_illust_series(id)
    

    if g.hx_request:
        return await render_block("illust_series.html.j2", "watchlist", data=data)
    
    return redirect(f["r"], code=303)


@bp.get("/_partials/series/<int:id>/material-you")
async def monet_series_banner(id: int):
    try:
        data = await artworks.get_illust_series(id)
    except Exception:
        return "", 404
    
    if not data.is_set_cover:
        return "", 400
    
    res = await monet.scheme_from_url(data.main.thumb_raw)
    return res, {"Content-Type": "text/css", "Cache-Control": "max-age=86400"}


@bp.get("/user/<user>/series/<int:id>")
async def useless(user: None, id: int):
    return redirect(url_for("artworks.series", id=id))

vixipy/templates/artworks.html.j2
{% extends "layouts/default.html.j2" %}
{% set title = _("%(work_name)s by %(author)s", work_name=work.title, author=work.authorName) %}

{% block head_additional %}
<meta property="og:title" content='{{_("%(work_name)s by %(author)s", work_name=work.title, author=work.authorName)}}'>
<meta property="og:site_name" content="{{config['INSTANCE_NAME']}}" />
<meta property="og:description" content="
👍 {{work.likeCount|numberformat}} ❤️ {{work.bookmarkCount|numberformat}} 💬 {{work.commentCount|numberformat}}

{% for tag in work.tags %}#{{tag.name}} {% endfor %}

{{work.description_stripped[:64]}}{% if work.description_stripped|length > 64%}...{% endif %}
" />

{#
<!-- Twitter Mosaic -->
{%- for page in pages if not page.page > 3 %}
<meta property="twitter:image" content="{{page.reg}}" />
{% endfor -%}
#}

{# Open Graph Image #}
<meta property="og:image" content="{{work.image_urls.regular}}" />
<meta property="twitter:card" content="summary_large_image" />

{% endblock %}

{% block content %}

{% if not g.hx_request %}

{% block root %}
<div id="artwork-root">
    <div class="content">
        <main>
            <div class="work-main">
                {% if g.hx_request %}
                <div class="pages-placeholder" hx-get="{{url_for('artworks._pages_p', id=work.id)}}" hx-trigger="load"
                    hx-swap="outerHTML">
                    {% include "components/spinner.html.j2" %}
                </div>
                {% else %}
                {% block pages %}
                <div class="pages">
                    {% for x in pages %}
                    <div class="page" id="{{x.page}}">
                        <div class="meta">
                        </div>
                        <a href="{{x.orig}}" target="_blank">
                            <img loading="lazy"
                                alt="{{_('Page %(page)d of %(total)d', page=x.page, total=pages|length)}}"
                                src="{{x.reg}}" {%if x.width and x.height%} width="{{x.width}}" height="{{x.height}}" {%
                                endif %}>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                {% endblock pages %}
                {% endif %}
            </div>
            {% if work.series_data %}
            <div class="series-data"></div>
            {% endif %}
            {#
            <div class="actions">
                <div class="wrapper"></div>
            </div>
            #}
        </main>
        <aside>
            {% if work.series_data %}
            <a class="series-link" href="{{url_for('artworks.series', id=work.series_data.id)}}">
                {{work.series_data.title}} #{{work.series_data.order}}
            </a>
            {% endif %}
            <h2>{{work.title}}</h2>
            {% if g.hx_request %}
            <div class="author" hx-get="{{url_for('artworks._author_p', id=work.authorId)}}" hx-trigger="load"
                hx-swap="outerHTML">
                <a class="img">
                    <img src="/proxy/s.pximg.net/common/images/no_profile_s.png">
                </a>
                <a>
                    {{_("Loading...")}}
                </a>
            </div>
            {% else %}
            {% block author %}
            <div class="author">
                <a class="img" href="{{url_for('users.user_profile', user=user.id)}}">
                    <img src="{{user.image}}">
                </a>
                <a href="{{url_for('users.user_profile', user=user.id)}}">
                    {{user.name}}
                </a>
            </div>
            {% endblock author %}
            {% endif %}
            <ul class="tags">
                {%- for x in work.tags -%}
                <li>
                    {%- if x.en or x.romaji -%}
                    <a href="{{url_for('search.search_main', query=x.name)}}">#{{x.name}} <span class="alternate">{{x.en
                            or x.romaji}}</span></a>
                    {%- else -%}
                    <a href="{{url_for('search.search_main', query=x.name)}}">#{{x.name}}</a>
                    {%- endif -%}
                </li>
                {%- endfor -%}
            </ul>
            {% if work.description_stripped|length > 0 %}
            <div class="description">
                <input type="checkbox" id="description-collapse" {% if work.description_stripped|length < 300%}checked{%
                    endif %}>
                <main>
                    {{work.description|safe}}
		</main>
		<label for="description-collapse">{{_("Show more...")}}</label>
	    </div>
	    {% endif %}
	    <ul class="attributes">
	        {%- if work.loginonly -%}
		<li>{{_("Sign in required")}}</li>
		{%- endif -%}
	        {%- if not work.xrestrict >= 1 and work.sl >= 4 -%}
	        <li class="error">{{_("Sensitivity Level: %(sl)d", sl=work.sl)}}</li>
		{%- endif -%}
		{%- if work.xrestrict >= 1 -%}
		<li class="error">{{work.xrestrict_friendlyname}}</li>
		{%- endif -%}
		{%- if work.ai -%}
		<li class="tertiary">{{_("AI Generated")}}</li>
		{%- endif -%}
		{%- if work.original -%}
		<li class="primary">{{_("Original")}}</li>
		{%- endif -%}
		{%- if work.isUgoira -%}
		<li class="secondary">{{_("Ugoira")}}</li>
		{%- endif -%}
	    </ul>
	    <div class="creation-date">{{work.uploadDate|datetimeformat}}</div>
        </aside>
    </div>
</div>


<main>
    {% if not g.hx_request %}
    {% block recommended %}
    {% import "components/artwork-entry.html.j2" as artwork_entry %}

    <section id="related">
        <h2>{{_("Related works")}}</h2>
        <div class="artwork-container">
            {% for r in recommend %}
            {{ artwork_entry.entry(r) }}
            {% endfor %}
        </div>
    </section>
    {% endblock recommended %}
    {% else %}
    <section id="related" hx-get="{{url_for('artworks._recommend_p', id=work.id)}}" hx-swap="outerHTML"
        hx-trigger="revealed">
        <h2>{{_("Related works")}}</h2>
        {% include "components/indicator-center.html.j2" %}
    </section>
    {% endif %}
</main>

{% endblock root %}

{% else %}
<div hx-get="{{url_for('artworks._root_p', id=work.id)}}" hx-trigger="load" hx-swap="outerHTML">
    {% include "components/content-loading.html.j2" %}
</div>
<style hx-get="{{url_for('api.gen_scheme_from_artwork', id=work.id)}}" hx-trigger="load" hx-swap="textContent"></style>
{% endif %}

</section>

{% endblock %}

{% block page_error %}
<div class="pages-error">
    <p>{{_("An error occurred trying to get the artwork pages")}}</p>
    <code>{{error.__class__.__name__}}: {{error}}</code>
</div>
{% endblock %}

vixipy/templates/content_warning.html.j2
{% extends "layouts/error_full.html.j2" %}
{% set title = _("Content Warning") %}
{% block content %}
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" clip-rule="evenodd"
        d="M12 4a2 2 0 00-2 2v6.5a2 2 0 104 0V6a2 2 0 00-2-2zm2.25 13.75a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
</svg>
<h1>{{_("Warning: Sensitive Content Ahead!")}}</h1>
<p>{{_("This page contains content not suitable for some people. Do you want to view it anyway?")}}</p>

<a id="back" class="label-button">{{_("Go back")}}</a>
<a hx-push-url="false" href="{{url_for('user_action.consent', r=url or '')}}" class="button primary">{{_("Proceed")}}</a>

<script>
    document.getElementById("back").onclick = (e) => {
        e.preventDefault();
        history.back();
    }
</script>
{% endblock %}

vixipy/templates/http_error.html.j2
{% extends "layouts/error_full.html.j2" %}
{% set title = error.code|string + " " + error.name %}

{% block content %}
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 4a2 2 0 00-2 2v6.5a2 2 0 104 0V6a2 2 0 00-2-2zm2.25 13.75a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z"/></svg>
<h1>{{error.code}}: {{error.name}}</h1>
<p>{{error.description}}</p>

<a id="back" class="label-button">{{_("Go back")}}</a>

<script>
    document.getElementById("back").onclick = (e)=>{
        e.preventDefault();
        history.back();
        window.close();
    }
</script>
{% endblock %}

vixipy/templates/index_logged_out.html.j2
{% extends "layouts/default.html.j2" %}
{% set title = _("Home") %}

{% from "components/artwork-entry.html.j2" import entry %}

{% block content %}
<main class="large">
    <section id="checkpoint">
        <h2>{{_("Ranking for %(date)s", date=data.date|dateformat)}}</h2>
        <div class="artwork-container">
            {% for x in data.contents %}
            {{ entry(x) }}
            {% endfor %}
        </div>
        <div class="button-pointer">
            <a href="/rankings" class="button neutral">
                {{_("View All")}}
            </a>
        </div>
    </section>
</main>
{% endblock %}

vixipy/templates/leave.html.j2
{% extends "layouts/error_full.html.j2" %}
{% block content %}
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 4a2 2 0 00-2 2v6.5a2 2 0 104 0V6a2 2 0 00-2-2zm2.25 13.75a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z"/></svg>
<h1>{{_("You are about to leave Vixipy.")}}</h1>
<p>{{_("Continuing will direct you to %(url)s", url=url)}}</p>

<a id="back" class="label-button">{{_("Go back")}}</a>
<a href="{{url}}" class="button primary">{{_("Continue to site")}}</a>

<script>
    document.getElementById("back").onclick = (e)=>{
        e.preventDefault();
        history.back();
        window.close();
    }
</script>
{% endblock %}

vixipy/templates/replies.html.j2
{% extends "layouts/default.html.j2" %}
{% set title=_("Comments") %}
{% from "components/comment.html.j2" import comment %}

{% block content %}
<main class="no-transition">
    <h2>{{_("Replies")}}</h2>
    <div id="comment-area">
        <div class="comments">
            {% for x in data.comments %}
            {{ comment(x) }}
            {% else %}
            {{_("No replies")}}
            {% endfor %}
        </div>
    </div>

    <div class="paginator">
        {%- set page = request.args.get("p", 1)|int -%}
        <a {% if page > 1 %}href="{{url_for('artworks.get_replies', id=id, p=page-1)}}"{% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="m432-480 156 156q11 11 11 28t-11 28q-11 11-28 11t-28-11L348-452q-6-6-8.5-13t-2.5-15q0-8 2.5-15t8.5-13l184-184q11-11 28-11t28 11q11 11 11 28t-11 28L432-480Z"/></svg>
        </a>
        <span>{{_("Page %(page)d", page=page)}}</span>
        <a {% if data.has_next %}href="{{url_for('artworks.get_replies', id=id, p=page+1)}}"{% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="M504-480 348-636q-11-11-11-28t11-28q11-11 28-11t28 11l184 184q6 6 8.5 13t2.5 15q0 8-2.5 15t-8.5 13L404-268q-11 11-28 11t-28-11q-11-11-11-28t11-28l156-156Z"/></svg>
        </a>
    </div>
</main>
{% endblock %}